### PR TITLE
feat: display all Netatmo stations

### LINKED ISSUE #81: Support for multiple Netatmo weather stations
Hi,

I have tried adding an additional variable for "device_id", to make it possible to add multiple Netatmo weather stations by adding multiple instances of the module in **~/MagicMirror/config/config.js**

https://dev.netatmo.com/resources/technical/reference/weather/getstationsdata

I can see the **device_id** when accessing the Netatmo API (see link above) but I'm struggling a bit getting it to work in this module.

 **~/MagicMirror/config/config.js**
```javascript
{
        module: 'netatmo',
        position: 'bottom_left', // the location where the module should be displayed
        config: {
                clientId: '', // your app id
                clientSecret: '', // your app secret
                refreshToken: '', // your generated refresh token
                deviceId: '' // MAC-address of your device (weather station)
        }
},
```

I added **device_id** to the **dataPayload** variable and added **deviceId** as a new variable to the config part of the **netatmo.js** – but I'm stuck at how to make the call for station data ask for the **device_id**. What am I doing wrong? :)

 **~/MagicMirror/modules/netatmo/netatmo.js**
```javascript
dataPayload: 'access_token={0}&device_id={1}' // added device_id
```

```javascript
 load: {
    token: function() {
      return Q($.ajax({
        type: 'POST',
        url: this.config.api.base + this.config.api.authEndpoint,
        data: this.config.api.authPayload.format(
            this.config.refreshToken,
            this.config.clientId,
            this.config.clientSecret,
            this.config.deviceId) // added deviceId
      }));
    },
    data: function(data) {
      // Log.info(this.name + " token loaded "+data.access_token);
      this.config.refreshToken = data.refresh_token;
      // call for station data
      return Q($.ajax({
        url: this.config.api.base + this.config.api.dataEndpoint,
        data: this.config.api.dataPayload.format(data.access_token) // how do I add deviceId here?
      }));
    }
  },
```

Thomas

### PR DESCRIPTION
**Pull request by CFenner**
With with PR all station the user has access to are displayed. Also station name is printed now **by default**. 

- To disable station names use `showStationName: false`.
- To filter stations to display use `moduleOrder` to filter out the modules you don't want to be displayed.

fixes #81 #98

### CODE REVIEW

**Comment by CFenner** [comment]
@kupraez @thomasberglund @aop-ch @Okiev check out this, I think it fits all your needs. Comment if otherwise.

**Comment by kupraez** [comment]
Hello, it doesn't work for me. The module shows loading...nothing else! I installed the module new and did the reconfiguration in the config?

**Comment by CFenner** [comment]
Die you run the [install command](https://github.com/CFenner/MMM-Netatmo#installation)?

**Comment by kupraez** [comment]
yes I did!

cd ~/MagicMirror/modules
git clone https://github.com/CFenner/MMM-Netatmo.git netatmocd netatmo
npm ci --production --ignore-scripts

my initial config:

{
module: 'netatmo',
position: 'bottom_left', // the location where the module should be displayed
header: 'Netatmo', // a header if you like one
config: {
clientId: '', // my app ID
clientSecret: '', // my app secret
username: '', // my netatmo username
password: '', // my netatmo password
}
},

**Comment by kupraez** [comment]
correction

**Comment by CFenner** [comment]
What does the browser log and the server log say?

**Comment by kupraez** [comment]
I'm a sailor, not a computer expert. I don't know what they're talking about or where i could expect that!

**Comment by kupraez** [comment]
Hello, I updated electron and now it is working. Unfortunately i haven’t enough space to use the vertical view. is there any possibility to add horizontally view in bubble-mode?

**Comment by CFenner** [comment]
> Is there any possibility to add horizontally view in bubble-mode?

No, not yet.

**Comment by kupraez** [comment]
Ok. I’m using the module as it is for now 1 year, maybe you will find a day or two in the future to get it done. Your work is fantastic…..thank you!

**Comment by aop-ch** [comment]
Hello
Thanks for evolving the module. It fits very good my need. I placed my three stations in two columns with eight sensors in total. :-). I'm using the bubble design.
I wish I could place the module names on top of the data block, as the module names looks for me like a title for the next data block.
Unfortunately couldn't figure out how the set the font size. Can you give me examples for xsmall und large values?
Kind regards,
Stefan

**Comment by CFenner** [comment]
@aop-ch the font can be changes via css classes, this are the default values:

```
    fontClassModuleName: 'xsmall',
    fontClassPrimary: 'large',
    fontClassSecondary: 'xsmall',
    fontClassMeasurement: 'xsmall',
```
 You can specify any css class you like, like classes you defined yourself in `custom.css` file or the [file default font classes](https://github.com/MichMich/MagicMirror/blob/a6cbc9f0ef46e4ba45e58e17f64f74410d8fe0b5/css/main.css#L62-L86).

**Comment by aop-ch** [comment]
Now I understand it. Thanks for the hint.

**Comment by CFenner** [comment]
Regarding the station naming, which version do you aim for?

name on top of the data section
Bildschirmfoto 2022-02-15 um 08 39 44

name on top of the whole module
Bildschirmfoto 2022-02-15 um 08 40 23

**Comment by aop-ch** [comment]
The second version with the name on top of the whole Module

**Pull request merged**
