### PR TITLE
feat(l10n): add ru translation

### PR DESCRIPTION
**Pull request by CFenner**
as provided in #148

### CODE REVIEW

**Comment by CFenner** [comment]
@Laz2516 can you have a look at this? I copied the translation from your post in #148.

**Comment by CFenner** [comment]
@Laz2516 is this still valid?

**Comment by Laz2516** [comment]
If you are talking about displaying pressure in mm Hg, then I can't check it yet. After all, the Netatmo module itself does not work due to the impossibility of authorization.

**Comment by CFenner** [comment]
No, some time ago you postet translation strings and with this I added them to the repository.

**Comment by Laz2516** [comment]
I see. Good. My translation for Russian is relevant. The only thing I can do is correct the cuts a little bit. To fit the width of the line. But this is possible precisely in my display of the module block. I will now connect to MM in another city and see my current translation settings.

**Comment by Laz2516** [comment]
"CO2": "CO<sub>2</sub>",
  "NOISE": "Шум",
  "HUMIDITY": "Влажн",
  "PRESSURE": "Давлен",
  "PRESSURE_TREND": "Давлен(изм)",
  "TEMPERATURE": "Темп-ра",
  "TEMP_TREND": "Темп-ра(изм)",
  "RAIN": "Дождь",
  "SUM_RAIN_1": "Дождь (1ч)",
  "SUM_RAIN_24": "Дождь (24ч)",
  "WINDSTRENGTH": "Ветер",
  "WINDANGLE": "Ветер(направл)",
  "GUSTSTRENGTH": "Порыв",
  "GUSTANGLE": "Направл",
  "UP": "рост",
  "STABLE": "стаб",
  "DOWN": "упало",
  "UNDEFINED": "неизвестно",
  "WIFI": "WiFi",
  "RADIO": "Ур.сигнала",
  "BATTERY": "Батарея",
  "LAST_MESSAGE": "Посл.соед"

**Comment by CFenner** [comment]
@all-contributors please add @Laz2516 for translation

**Comment by Laz2516** [comment]
Should I confirm something somewhere?))
Permission to use my translation..)))

**Comment by CFenner** [comment]
No, I just wanted to know is the translation I added is still the one to use, see [files tab](https://github.com/CFenner/MMM-Netatmo/pull/185/files).

**Comment by Laz2516** [comment]
Yes )

**Pull request merged**
