### PR TITLE
v2.1.0: Token read/write // refact code

### PR DESCRIPTION
**Pull request by bugsounet**
# Change Log:

 * netatmo.js:
     * Review start rules and (please) don't use `self`... use `this`
     * `start()` send now config to `helper.js` and use it (without self!)
     * delete not needed payload on socket notification send (already sended on init)
     * delete error 403 loop !!!
 * helper.js:
     * make init function for init all value with `this`
     * check if all needed value are set in config (clientId, clientSecret, refresh_token)
     * Create a `token.json` file when Authenticate done (with new credentials)
     * Rules on first start: use `refresh_token` of config for autenticate
     * Next start/restart: use `token.json` file for authenticate
     * use new value for better management: `this.clientId`, `this.clientSecret`, `this.refreshToken`
     * add rules for refresh token
     * Set refresh token to 1 min before netatmo expire token response
  
  * Delete Deps:
     * `@ungap/url-search-params` : not needed with node > 18
    
  * Add eslint rules:
     *  `eslint.config.js` from my common modules
  
  * Add Deps:
     * `@eslint/js`
     * `@stylistic/eslint-plugin`
  
  * package.json
     * review `validate:js` script
     * review `fix:js` script
  
  * lint (with eslint.config.js)
     * node_helper.js
     * helper.js
     * netatmo.js
     * helper.test.js is ignored (can't works now but i keep it... up to @CFenner to clean it)

   * workflows:
     *  delete `helper.test.js` / `.env.template` : can't works now with new netatmo API Rules
     * update validation rules
     * Fix: renovate.json (for validate:json)

  * Add `token.json` to `.gitignore`
 
  * Update README.md
    * delete: `cd netatmo && npm ci --production --ignore-scripts`  --> is now not needed
    *  **No special dependencies and no others commands are now needed!**

-----
  * Tested:
    * by @bugsounet with `mockData: true` : ok
    * by @Lusbueb69 with full credentials: ok

### CODE REVIEW

**Comment by bugsounet** [comment]
Your codes rules are really weird ;)

up to you to finish ;)

**Comment by bugsounet** [comment]
I will see that add auto-refresh token
It's not added actually

**Comment by Lusbueb69** [comment]
> maybe solve #380
> 
> I can't test better actually because i have no station
> 
> I just apply read/write token rules like my MMM-NetatmoThermostat module
> 
> @CFenner can you test it ?

what is the right way to test your code adjustments? If I make the adjustments manually and restart MM, then nothing is displayed anymore. If I remove your adjustments and restart MM, then everything works fine.

**Comment by bugsounet** [comment]
Right, I rewrite many thing...

Now result is on first start:

[2024-06-22 10:01:23.027] [LOG]   Connecting socket for: netatmo 
[2024-06-22 10:01:23.028] [LOG]   Netatmo helper started ... 
[2024-06-22 10:01:23.028] [LOG]   Sockets connected & modules started ... 
[2024-06-22 10:01:23.138] [LOG]   Launching application. 
[2024-06-22 10:01:24.173] [LOG]   Netatmo: using refresh_token from config 
[2024-06-22 10:01:24.173] [LOG]   Netatmo: Initialized 
[2024-06-22 10:01:24.498] [LOG]   Netatmo: Authenticated 
[2024-06-22 10:01:24.498] [LOG]   Netatmo: token.json was written successfully 
[2024-06-22 10:01:24.501] [LOG]   Netatmo: New Token Expire Saturday, June 22, 2024 1:01 PM 
```

on restart:

```
[2024-06-22 10:03:01.312] [LOG]   Connecting socket for: netatmo 
[2024-06-22 10:03:01.312] [LOG]   Netatmo helper started ... 
[2024-06-22 10:03:01.312] [LOG]   Sockets connected & modules started ... 
[2024-06-22 10:03:01.419] [LOG]   Launching application. 
[2024-06-22 10:03:02.467] [LOG]   Netatmo: using token.json file 
[2024-06-22 10:03:02.467] [LOG]   Netatmo: Initialized 
[2024-06-22 10:03:02.792] [LOG]   Netatmo: Authenticated 
[2024-06-22 10:03:02.793] [LOG]   Netatmo: token.json was written successfully 
[2024-06-22 10:03:02.797] [LOG]   Netatmo: New Token Expire Saturday, June 22, 2024 1:03 PM 
```

I will force refresh token and see what happen :=)

**Comment by bugsounet** [comment]
(Note: I really don't agree with your rules of the test workflows suite... thx to review your rules)

**Comment by Lusbueb69** [comment]
@bugsounet if you want, i can share you a temporary API from my NETATMO, just send my a Message and i will send you all required codes.

**Comment by bugsounet** [comment]
@Lusbueb69 You can try it by your self ;)

try this in `netatmo` module folder

```sh
git fetch origin pull/382/head:bugsounetTest
git checkout -f bugsounetTest
```
If any `token.json` file exist ---> delete it
Connect to netatmo connect and make like readme says (like first configuration time)

next restart must use token file

**Comment by Lusbueb69** [comment]
i have choose an other way (because i'm a dummy-user):

- `pm2 stop mm`
- rename the existing folder `netatmo` to `netatmo.240622`
- `cd ~/MagicMirror/modules && git clone https://github.com/bugsounet/MMM-Netatmo netatmo`
- `cd netatmo && npm ci --production --ignore-scripts`
- generate a new [refresh-token](https://dev.netatmo.com/apps/) an insert the new token in `config.js`
- `pm2 start mm`

i'm so happy, everything works fine, still after a RPI reboot or a `pm2 restart mm`.

**Comment by bugsounet** [comment]
@CFenner: I'm going to stop there, it remains validate:md to do

**Comment by CFenner** [comment]
Really appreciate this PR, thank!

> Your codes rules are really weird ;)

I use `eslint-config-standard` so that I do not need to deal with the rules configuration. One can always argue about the rules, it's just personal style that I don't want to care.

**Review by CFenner — APPROVED** [review]
👍

**Comment by CFenner** [comment]
@all-contributors please add @bugsounet for code, bug, review

**Pull request merged**
